# Site settings
title: Zibo Li
email: zibo.li25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This is Zibo's blog
url: "http://zli25.com" # the base hostname & protocol for your site

# Build settings
markdown: rdiscount
paginate: 8
permalink: /:title
author_info: <a href="http://beiyuu.com/">BeiYuu</a>
